apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-broken

resources:
- deployment.yaml
- sa-secret.yaml
- sa.yaml
- service.yaml
- ingress.yaml
- namespace.yaml
- networkpolicy.yaml